// beers
export const BEERS_SET_COLLECTION = "BEERS_SET_COLLECTION";

// taps
export const TAPS_SET_COLLECTION = "TAPS_SET_COLLECTION";

export const TAPS_ADD_REQUEST = "TAPS_ADD_REQUEST";
export const TAPS_ADD_SUCCESS = "TAPS_ADD_SUCCESS";
export const TAPS_ADD_FAILURE = "TAPS_ADD_FAILURE";

export const TAPS_UPDATE_REQUEST = "TAPS_UPDATE_REQUEST";
export const TAPS_UPDATE_SUCCESS = "TAPS_UPDATE_SUCCESS";
export const TAPS_UPDATE_FAILURE = "TAPS_UPDATE_FAILURE";

export const TAPS_MOVE_UP_REQUEST = "TAPS_MOVE_UP_REQUEST";
export const TAPS_MOVE_UP_SUCCESS = "TAPS_MOVE_UP_SUCCESS";
export const TAPS_MOVE_UP_FAILURE = "TAPS_MOVE_UP_FAILURE";

export const TAPS_MOVE_DOWN_REQUEST = "TAPS_MOVE_DOWN_REQUEST";
export const TAPS_MOVE_DOWN_SUCCESS = "TAPS_MOVE_DOWN_SUCCESS";
export const TAPS_MOVE_DOWN_FAILURE = "TAPS_MOVE_DOWN_FAILURE";

export const TAPS_DELETE_REQUEST = "TAPS_DELETE_REQUEST";
export const TAPS_DELETE_SUCCESS = "TAPS_DELETE_SUCCESS";
export const TAPS_DELETE_FAILURE = "TAPS_DELETE_FAILURE";
