// beers
export const BEERS_SET_COLLECTION = "BEERS_SET_COLLECTION";

export const BEERS_ADD_REQUEST = "BEERS_ADD_REQUEST";
export const BEERS_ADD_SUCCESS = "BEERS_ADD_SUCCESS";
export const BEERS_ADD_FAILURE = "BEERS_ADD_FAILURE";

export const BEERS_UPDATE_REQUEST = "BEERS_UPDATE_REQUEST";
export const BEERS_UPDATE_SUCCESS = "BEERS_UPDATE_SUCCESS";
export const BEERS_UPDATE_FAILURE = "BEERS_UPDATE_FAILURE";

export const BEERS_DELETE_REQUEST = "BEERS_DELETE_REQUEST";
export const BEERS_DELETE_SUCCESS = "BEERS_DELETE_SUCCESS";
export const BEERS_DELETE_FAILURE = "BEERS_DELETE_FAILURE";

// taps
export const TAPS_SET_COLLECTION = "TAPS_SET_COLLECTION";

export const TAPS_ADD_REQUEST = "TAPS_ADD_REQUEST";
export const TAPS_ADD_SUCCESS = "TAPS_ADD_SUCCESS";
export const TAPS_ADD_FAILURE = "TAPS_ADD_FAILURE";

export const TAPS_UPDATE_REQUEST = "TAPS_UPDATE_REQUEST";
export const TAPS_UPDATE_SUCCESS = "TAPS_UPDATE_SUCCESS";
export const TAPS_UPDATE_FAILURE = "TAPS_UPDATE_FAILURE";

export const TAPS_MOVE_UP_REQUEST = "TAPS_MOVE_UP_REQUEST";
export const TAPS_MOVE_UP_SUCCESS = "TAPS_MOVE_UP_SUCCESS";
export const TAPS_MOVE_UP_FAILURE = "TAPS_MOVE_UP_FAILURE";

export const TAPS_MOVE_DOWN_REQUEST = "TAPS_MOVE_DOWN_REQUEST";
export const TAPS_MOVE_DOWN_SUCCESS = "TAPS_MOVE_DOWN_SUCCESS";
export const TAPS_MOVE_DOWN_FAILURE = "TAPS_MOVE_DOWN_FAILURE";

export const TAPS_DELETE_REQUEST = "TAPS_DELETE_REQUEST";
export const TAPS_DELETE_SUCCESS = "TAPS_DELETE_SUCCESS";
export const TAPS_DELETE_FAILURE = "TAPS_DELETE_FAILURE";

// events
export const EVENTS_SET_COLLECTION = "EVENTS_SET_COLLECTION";

// past events
export const PASTEVENTS_ADD_REQUEST = "PASTEVENTS_ADD_REQUEST";
export const PASTEVENTS_ADD_SUCCESS = "PASTEVENTS_ADD_SUCCESS";
export const PASTEVENTS_ADD_FAILURE = "PASTEVENTS_ADD_FAILURE";

// User
export const USER_SET_CURRENT_USER = "USER_SET_CURRENT_USER";
export const USER_REMOVE_CURRENT_USER = "USER_REMOVE_CURRENT_USER";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";
