// beers
export const BEERS_SET_COLLECTION = "BEERS_SET_COLLECTION";

// taps
export const TAPS_SET_COLLECTION = "TAPS_SET_COLLECTION";

// events
export const EVENTS_SET_COLLECTION = "EVENTS_SET_COLLECTION";

// past events
export const PASTEVENTS_ADD_REQUEST = "PASTEVENTS_ADD_REQUEST";
export const PASTEVENTS_ADD_SUCCESS = "PASTEVENTS_ADD_SUCCESS";
export const PASTEVENTS_ADD_FAILURE = "PASTEVENTS_ADD_FAILURE";

// User
export const USER_SET_CURRENT_USER = "USER_SET_CURRENT_USER";
export const USER_REMOVE_CURRENT_USER = "USER_REMOVE_CURRENT_USER";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";

export const SET_AUTH = "SET_AUTH";
