source 'https://rubygems.org'

gem 'dotenv-rails', :groups => [:development, :test]
gem 'rails', '4.2.5'
gem 'rails-api'

gem 'acts_as_list'
gem 'bcrypt', '~> 3.1.7'
gem 'knock'
gem 'rabl'
gem 'rack-cors'
gem 'sqlite3'
gem 'koala', '~> 2.2'

group :development do
  gem 'annotate'
  gem 'spring'
end
