source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.1.0'

gem 'acts_as_list'
gem 'aws-sdk-s3', '~> 1'
gem 'bcrypt', '~> 3.1.7'
gem 'dotenv-rails'#, :groups => [:development, :test]
gem 'faraday'
gem 'hashie'
gem 'json', "~> 2"
gem 'knock'
gem 'koala', '~> 2.2'
gem 'mailgun-ruby', '~>1.1.6'
gem 'puma', '~> 3.7'
gem 'rabl'
gem 'rack-cors'
gem 'sqlite3'

group :development do
  gem 'annotate'
  gem 'listen'
  gem 'capistrano', '~> 3.10'
  gem 'capistrano-rvm',     require: false
  gem 'capistrano-rails',   require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano3-puma',   require: false
end


gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

